# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
with_docs = true
patch_file = "src/schema.patch"

[migrations_directory]
dir = "migrations"
