# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
with_docs = true
custom_type_derives = ["diesel::query_builder::QueryId"]
# filter = { except_tables = ["_BadgeToUser", "_BotToTag", "_BotToUser"] }

[migrations_directory]
dir = "migrations"
