[package]
name = "services"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true
tracing.workspace = true
jsonwebtoken.workspace = true

[features]
votes = []
reviews = []
banners = []
