name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: next-7
      - name: Use Node.js v20
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-frozen-lockfile
      - name: Run Linter
        run: pnpm lint

  Building:
    name: Compile source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: next-7
      - name: Use Node.js v20
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-frozen-lockfile
      - name: Build Code
        run: pnpm build
