name: "Sync labels"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

permissions:
  issues: write
  contents: read

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Refactor labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2
        with:
          config-file: ${{ github.workspace }}/.github/labels.yml
          delete-other-labels: true
